Vista de ajustes + wireframe + facetado + texturas on/off + luces de colores  + velocidad del juego
Frodo2412/playing-with-open-gl pull request #40
Opened 2024-04-24 23:02 UTC by matiasencion

vista de ajustes:

![image](https://github.com/Frodo2412/playing-with-open-gl/assets/108829786/ae10060b-d450-470e-976b-81c4bbeb4cd2)

la velocidad del juego es una variable que puede tener 3 valores y cambia la velocidad de movimiento del personaje y la camara, a futuro cuando tengamos animaciones tambien las tiene que cambiar

wireframe:

![image](https://github.com/Frodo2412/playing-with-open-gl/assets/108829786/f1ba9eba-d7c7-4f43-9f02-d69b77c5323b)

sin texturas:

![image](https://github.com/Frodo2412/playing-with-open-gl/assets/108829786/4ffef0e1-7f06-4775-8fc5-58aae44cda80)

facetado:

![image](https://github.com/Frodo2412/playing-with-open-gl/assets/108829786/bed2c564-7a72-405c-8072-2c235a40d137)

luces de colores:

![image](https://github.com/Frodo2412/playing-with-open-gl/assets/108829786/645988a7-165e-4d30-8454-8e38523ef9ca)

![image](https://github.com/Frodo2412/playing-with-open-gl/assets/108829786/e722fb75-4183-4200-80a4-7ebbddceed14)

![image](https://github.com/Frodo2412/playing-with-open-gl/assets/108829786/f82e8eda-1592-45c3-810d-c5642c2c7d42)

![image](https://github.com/Frodo2412/playing-with-open-gl/assets/108829786/ba9b9b9c-c8aa-42af-90d7-86a279f2c2d9)

2024-04-24 23:30 UTC, Frodo2412 reviewed
Also, puede ser que las luces nos hayan arruinado el sombreado del piso?

2024-04-24 23:30 UTC, Frodo2412 commented on OpenGL-basico/utils/renderer.cpp
> +}
Hay 140 lineas de codigo aca y entiendo 0 de lo que pasa. Podemos refactorizar esto para que quede mas entendible?

2024-04-24 23:30 UTC, Frodo2412 commented on main.cpp
> +    int time = 0;
Eso creo que es lo que hace el clock. Tipo usa la misma funcion y todo.

2024-04-24 23:40 UTC, Frodo2412 commented on main.cpp
> +    const auto blue_settings_texture = texture_loader::load_texture("../assets/textures/settings/azul.jpg");
Todo esto estaria bueno sacarlo de hacer. Tener una clase `menu` asi como tenemos un `game_hud`.

2024-04-24 23:51 UTC, Frodo2412 requested changes

2024-04-24 23:51 UTC, Frodo2412 commented on main.cpp
> +            settings::get_instance()->set_winWidth(winWidth);
Esto no es necesario asignarlo. En general no es bueno hacer cosas "por las dudas" porque anda a saber como se diseña ese feature despues. Y se me ocurre que tampoco va a ser necesario esto.

2024-04-24 23:58 UTC, Frodo2412 commented
Me baje el codigo y hay pila de warnings tipo parametros sin usar. Le voy a pegar un refactor y lo subo a otra rama.

2024-04-25 00:06 UTC, matiasencion commented on OpenGL-basico/utils/renderer.cpp
> +}
esto se encarga de dibujar cada elemento en pantalla y que cambien segun cuales estan activadas o no, tipo es todo visual. No creo que haya otra forma de hacerlo, solo son cuadrados de opengl y texturas

2024-04-25 00:09 UTC, matiasencion commented on main.cpp
> +            settings::get_instance()->set_winWidth(winWidth);
yo me avive y lo puse porque no da armar cada elemento del menu hardcodeado y despues tengamos que cambiar la resolucion por cualquier motivo y no ande bien, ademas es una opcion que suma mucho mas de lo que resta

2024-04-25 00:10 UTC, matiasencion commented on main.cpp
> +    const auto blue_settings_texture = texture_loader::load_texture("../assets/textures/settings/azul.jpg");
lo puedo poner el settings mismo

2024-04-25 00:10 UTC, matiasencion commented on main.cpp
> +    int time = 0;
si, lo cambio

2024-04-25 00:45 UTC, matiasencion commented
me fije lo de los warnings y los corregi

2024-04-25 01:14 UTC, Frodo2412 commented on main.cpp
> +            settings::get_instance()->set_winWidth(winWidth);
Precisamente porque no da que no ande bien esto no esta bueno dejarlo asi. Ponele que alguien mas viene y agarra el ticket de cambiar la resolucion, pero en vez de cambiar las variables globales que hay ahi arriba cambia los settings. Ese cambio ahora no vale nada porque cada frame se sobre escriben. En general la buena practica es tener una sola fuente de verdad para las cosas.

2024-04-25 01:17 UTC, Frodo2412 commented on OpenGL-basico/utils/renderer.cpp
> +}
En mi rama aparte lo estoy trabajando un cacho y creo que se puede acortar muchismo el codigo aca.

Fijate que en realidad lo que haces es:

```cpp 
   // Segun el estado bindeo la textura
    switch (settings->get_instance()->get_light_color())
    {
        case day:
            glBindTexture(GL_TEXTURE_2D, day_settings_texture.get_texture_id());
            break;
        case night:
            glBindTexture(GL_TEXTURE_2D, night_settings_texture.get_texture_id());
            break;
        case red:
            glBindTexture(GL_TEXTURE_2D, red_settings_texture.get_texture_id());
            break;
        case green:
            glBindTexture(GL_TEXTURE_2D, green_settings_texture.get_texture_id());
            break;
        case blue:
            glBindTexture(GL_TEXTURE_2D, blue_settings_texture.get_texture_id());
            break;
    }
   // Dibujo el boton
       glBegin(GL_QUADS);
    glTexCoord2f(0,0);
    glVertex3f(enabled_coord_x,enabled_coord_y,1);
    glTexCoord2f(1,0);
    glVertex3f(enabled_coord_x + 100,enabled_coord_y,1);
    glTexCoord2f(1,1);
    glVertex3f(enabled_coord_x + 100,enabled_coord_y + 50,1);
    glTexCoord2f(0,1);
    glVertex3f(enabled_coord_x,enabled_coord_y + 50,1);
    glEnd();
```

Y ahi en el medio haces unas cuentas que entiendo son para saber donde dibujar el proximo boton. Eso ahi sin escarbar mucho es una abstraccion que se puede hacer a un metodo aparte que ya simplifica un monton este codigo.

Y si queres darle vuelta un poco mas hay una clase `button` por aca escondida

2024-04-26 11:52 UTC, Frodo2412 approved these changes

2024-04-26 12:59 UTC, merged